# Generated by Django 3.1.5 on 2021-12-31 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_by',
            new_name='created_by',
        ),
    ]
